kind: pipeline
name: php-7.3.7

steps:
  - name: chown # we need to do this since our test container runs with www-data and drone clones with root
    image: debian:stretch-slim
    user: root
    commands:
      - chown -R www-data:www-data /drone/src

  - name: test
    image: quay.io/presslabs/php-runtime:7.3.7
    commands:
      - composer install --no-ansi --prefer-dist
      - make test
    environment:
      DB_TEST_HOST: wordpress
      DB_TEST_NAME: wordpress
      DB_TEST_PASSWORD: wordpress
      DB_TEST_USER: wordpress
    when:
      event:
      - push

services:
  - name: database
    image: percona:5.7
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: insecure-root-password-but-good-for-ci
      MYSQL_USER: wordpress
